name: Build and Push to ECR

on:
  push:
    branches: ["develop"]
    paths-ignore: ['**.md', 'docs/**', '.vscode/**', '.env.example', '.gitignore', '.dockerignore', '.prettierrc', 'eslint.config.mjs']

  workflow_dispatch:

jobs:
  build:
    uses: cura-fitness/cura-devops/.github/workflows/build_push_dev.yml@master
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY:        ${{ secrets.ECR_REPOSITORY }}
      PAT:                   ${{ secrets.PAT }}