name: Build and Push to ECR

on:
  push:
    branches: ["develop"]
    paths-ignore: ['**.md', 'docs/**', '.vscode/**', '.env.example', '.gitignore', '.dockerignore', '.prettierrc', 'eslint.config.mjs']
  
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - id: aws-setup
        uses: cura-fitness/cura-devops/.github/actions/aws-setup@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.aws-setup.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          IMAGE_TAG=dev-sha-${GITHUB_SHA::7}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:dev
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev

      - name: Trigger DevOps Workflow
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl -X POST \
            --fail-with-body \
            -H "Authorization: Bearer ${PAT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/cura-fitness/cura-devops/actions/workflows/deploy_dev.yml/dispatches \
            -d '{"ref":"master"}'
